version: "3.9"

services:
  mysql:
    image: mysql:8.3
    container_name: lifehub_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lifehub
    ports:
      - "3306:3306"
    volumes:
      - lifehub_db:/var/lib/mysql

  backend:
    build: ./backend
    container_name: lifehub_backend
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql:3306/lifehub
      SECRET_KEY: change_me
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  lifehub_db:
